name: Generate Sponsors README
on:
  workflow_dispatch:
  schedule:
    - cron: 30 15 * * 0-6
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Generate Sponsors 💖
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.ORG_REPO_TOKEN }}
          file: 'README.md'

      - name: Create Pull Request 🚀
        uses: peter-evans/create-pull-request@v4
        with:
          title: "feat: update sponsors"
          body: "Sponsors now are up to date"
          commit-message: "feat: update sponsors"
          delete-branch: true
          base:  master
